bbms_v2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('blog/', include('blog.urls'))
]

blog/urls.py
from django.urls import path, include
from blog import views
app_name = 'blog'

urlpatterns = [
    path('about/post<int:post_id>/', views.about, name='about'),
    path('delete/post=<int:post_id>/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    path('update/post=<int:post_id>/', views.update_blog, name='update'),
    path('comment/at/post=<int:post_id>/', views.add_comment, name='add_comment'),
    path('reply/at/comment=<int:comment_id>/', views.add_reply, name='add_reply'),
    path('delete/comment=<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('delete/reply=<int:reply_id>/', views.delete_reply, name='delete_reply'),
    path('edit/comment=<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('edit/reply=<int:reply_id>/', views.edit_reply, name='edit_reply'),

]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [

    path('', views.home, name='home'),
    path('old/', views.old_home, name="old_post"),
    path('signup/donor/', views.sig_don, name='sig_don'),
    path('create/donor/', views.crp_don, name='crp_don'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('update/profile/', views.update, name='update'),
    path('signup/hospital/', views.sig_hos, name='sig_hos'),
    path('create/hospital/', views.crp_hos, name='crp_hos'),
    path('hospital/search/donor/', views.search_donor, name='search_donor'),
    path('request/donor<int:donor_user_id>/bg<str:blood_group>/city<str:city>/', views.make_request, name='make_request'),
    # blood_group, city, request_id
    path('undo/req/bg<str:blood_group>/city<str:city>/id=<int:request_id>/', views.undo_request, name='undo_request'),
    path('donor/new/request/view/', views.request_view_donor, name='request_view_donor'),
    path('donor/accept/request/request_id=<int:request_id>/', views.accept_request, name='accept_request'),
    path('donor/reject/request/request_id=<int:request_id>/', views.reject_request, name='reject_request'),
    path('hospital/view/repo/', views.view_repo, name='view_repo'),
    path('hospital/add/blood/repo', views.add_blood, name='add_blood'),
    path('hospital/remove/blood/repo', views.remove_blood, name='remove_blood'),
    path('hospital/active/request/', views.active_reqs, name='active_reqs'),
    path('hospital/approve/req=<int:request_id>/', views.approve, name='approve'),
    path('hospital/history/', views.view_history, name='view_history'),
    path('tongle', views.change, name='tongle'),
]

blog/models.py
from django.db import models
from users.models import CustomUser
# Create your models here.

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user_id = models.IntegerField(default=-1)
    post_id = models.IntegerField(default=-1)
    com = models.TextField(max_length=300)
    date_commented = models.DateTimeField(default=timezone.now)


class Reply(models.Model):
    user_id = models.IntegerField(default=-1)
    comment_id = models.IntegerField(default=-1)
    reply_to = models.TextField(max_length=300)
    date_commented = models.DateTimeField(default=timezone.now)

blog/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.utils import timezone

from .models import *





def delete(request, post_id):
    blog_post = Post.objects.get(id=post_id)
    context = {
        'message': "Post has benn successfully deleted",
        'posts': Post.objects.order_by('-date_posted'),
        'title': "VowForRed -Home",

    }
    blog_post.delete()
    return render(request, 'blog/home.html', context)


def about(request, post_id):
    raw_comments = Comment.objects.filter(post_id=post_id)
    comments = []
    for raw_comment in raw_comments:
        raw_replies = Reply.objects.filter(comment_id=raw_comment.id)
        rep_ripe = []
        for rep in raw_replies:
            x = rep.user_id
            user_name = CustomUser.objects.get(id=x).username
            rep_ripe.append((rep, user_name))
        x = raw_comment.user_id
        user_name = CustomUser.objects.get(id=x).username
        comments.append((raw_comment, user_name, rep_ripe))

    post_t = Post.objects.get(id=post_id)

    context = {
        'post': post_t,
        'days': (datetime.now().date() - post_t.date_posted.date()).days,
        'comments': comments,
        'title': "VowForRed -About",

    }
    return render(request, 'blog/about.html', context)


def add(request):
    if request.method == "POST":
        new_post = Post()
        new_post.author = request.user
        new_post.title = request.POST["title"]
        new_post.content = request.POST["content"]
        new_post.save()
        context = {
            'posts': Post.objects.order_by('-date_posted'),
            'message': "Post has been successfully created",
            'title': "VowForRed -Home",


        }
        return render(request, 'blog/home.html', context)
    else:
        return render(request, 'blog/add.html', {'title': "VowForRed -Add Post", })


def update_blog(request, post_id):
    if request.method == "POST":
        post = Post.objects.get(id=post_id)
        post.title = request.POST["title"]
        post.content = request.POST["content"]
        post.save()
        context = {
            'posts': Post.objects.order_by('-date_posted'),
            'message': "Post has benn successfully updated",
            'title': "VowForRed -Update Post",


        }
        return render(request, 'blog/home.html', context)
    else:
        context = {
            'post': Post.objects.get(id=post_id),
            'title': "VowForRed -Update Post",

        }
        return render(request, 'blog/update.html', context)


def add_comment(request, post_id):
    if request.method == "POST":
        com = request.POST["comment"]
        new_comment = Comment()
        new_comment.post_id = post_id
        new_comment.user_id = request.user.id
        new_comment.com = com
        new_comment.user_name = request.user.username
        new_comment.save()

        raw_comments = Comment.objects.filter(post_id=post_id)
        comments = []
        for raw_comment in raw_comments:
            raw_replies = Reply.objects.filter(comment_id=raw_comment.id)
            rep_ripe = []
            for rep in raw_replies:
                x = rep.user_id
                user_name = CustomUser.objects.get(id=x).username
                rep_ripe.append((rep, user_name))
            x = raw_comment.user_id
            user_name = CustomUser.objects.get(id=x).username
            comments.append((raw_comment, user_name, rep_ripe))

        post_t = Post.objects.get(id=post_id)
        context = {
            'post': post_t,
            'days': (datetime.now().date() - post_t.date_posted.date()).days,
            'comments': comments,
            'title': "VowForRed -About",

        }

        return render(request, 'blog/about.html', context)


def add_reply(request, comment_id):
    if request.method == "POST":
        new_rep = Reply()
        new_rep.comment_id = comment_id
        new_rep.user_id = request.user.id
        new_rep.reply_to = request.POST["reply_to"]
        new_rep.save()
        post_id = Comment.objects.get(id=comment_id).post_id
        raw_comments = Comment.objects.filter(post_id=post_id)
        comments = []
        for raw_comment in raw_comments:
            raw_replies = Reply.objects.filter(comment_id=raw_comment.id)
            rep_ripe = []
            for rep in raw_replies:
                x = rep.user_id
                user_name = CustomUser.objects.get(id=x).username
                rep_ripe.append((rep, user_name))
            x = raw_comment.user_id
            user_name = CustomUser.objects.get(id=x).username
            comments.append((raw_comment, user_name, rep_ripe))

        post_t = Post.objects.get(id=post_id)
        context = {
            'post': post_t,
            'days': (datetime.now().date() - post_t.date_posted.date()).days,
            'comments': comments,
            'title': "VowForRed -About",

        }

        return render(request, 'blog/about.html', context)


def delete_comment(request, comment_id):
    reply_set = Reply.objects.filter(comment_id=comment_id)
    for rep in reply_set:
        rep.delete()
    com = Comment.objects.get(id=comment_id)
    post_id = com.post_id
    com.delete()
    raw_comments = Comment.objects.filter(post_id=post_id)
    comments = []
    for raw_comment in raw_comments:
        raw_replies = Reply.objects.filter(comment_id=raw_comment.id)
        rep_ripe = []
        for rep in raw_replies:
            x = rep.user_id
            user_name = CustomUser.objects.get(id=x).username
            rep_ripe.append((rep, user_name))
        x = raw_comment.user_id
        user_name = CustomUser.objects.get(id=x).username
        comments.append((raw_comment, user_name, rep_ripe))

    post_t = Post.objects.get(id=post_id)

    context = {
        'post': post_t,
        'days': (datetime.now().date() - post_t.date_posted.date()).days,
        'comments': comments,
        'title': "VowForRed -About",

    }
    return render(request, 'blog/about.html', context)


def delete_reply(request, reply_id):
    rep = Reply.objects.get(id=reply_id)
    rep.delete()
    comment_id = rep.comment_id
    com = Comment.objects.get(id=comment_id)
    post_id = com.post_id
    raw_comments = Comment.objects.filter(post_id=post_id)
    comments = []
    for raw_comment in raw_comments:
        raw_replies = Reply.objects.filter(comment_id=raw_comment.id)
        rep_ripe = []
        for rep in raw_replies:
            x = rep.user_id
            user_name = CustomUser.objects.get(id=x).username
            rep_ripe.append((rep, user_name))
        x = raw_comment.user_id
        user_name = CustomUser.objects.get(id=x).username
        comments.append((raw_comment, user_name, rep_ripe))

    post_t = Post.objects.get(id=post_id)

    context = {
        'post': post_t,
        'days': (datetime.now().date() - post_t.date_posted.date()).days,
        'comments': comments,
        'title': "VowForRed -About",

    }
    return render(request, 'blog/about.html', context)


def edit_comment(request, comment_id):
    if request.method == "POST":
        com = Comment.objects.get(id=comment_id)
        com.com = request.POST["com"]
        com.save()
        post_id = com.post_id

        raw_comments = Comment.objects.filter(post_id=post_id)
        comments = []
        for raw_comment in raw_comments:
            raw_replies = Reply.objects.filter(comment_id=raw_comment.id)
            rep_ripe = []
            for rep in raw_replies:
                x = rep.user_id
                user_name = CustomUser.objects.get(id=x).username
                rep_ripe.append((rep, user_name))
            x = raw_comment.user_id
            user_name = CustomUser.objects.get(id=x).username
            comments.append((raw_comment, user_name, rep_ripe))

        post_t = Post.objects.get(id=post_id)

        context = {
            'post': post_t,
            'days': (datetime.now().date() - post_t.date_posted.date()).days,
            'comments': comments,
            'title': "VowForRed -About",


        }
        return render(request, 'blog/about.html', context)


def edit_reply(request, reply_id):

    if request.method == "POST":
        rep = Reply.objects.get(id=reply_id)
        rep.reply_to = request.POST["reply_to"]
        rep.save()
        print(rep)
        post_id = Comment.objects.get(id=rep.comment_id).post_id

        raw_comments = Comment.objects.filter(post_id=post_id)
        comments = []
        for raw_comment in raw_comments:
            raw_replies = Reply.objects.filter(comment_id=raw_comment.id)
            print(raw_replies)
            rep_ripe = []
            for rep in raw_replies:
                x = rep.user_id
                user_name = CustomUser.objects.get(id=x).username
                rep_ripe.append((rep, user_name))
            x = raw_comment.user_id
            user_name = CustomUser.objects.get(id=x).username
            comments.append((raw_comment, user_name, rep_ripe))

        post_t = Post.objects.get(id=post_id)
        print(comments)
        context = {
            'post': post_t,
            'days': (datetime.now().date() - post_t.date_posted.date()).days,
            'comments': comments,
            'title': "VowForRed -About",

        }
        return render(request, 'blog/about.html', context)

blog/templates/blog/add.html
{% extends 'blog/base.html' %}

{% block blog_container %}
    <form action="{% url 'blog:add' %}"  method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleFormControlInput1" >Enter Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Enter Post Title" name="title" required>
        </div>

        <div class="form-group">
            <label for="exampleFormControlTextarea1" >Enter Content</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="20" name="content" required>

            </textarea>
        </div>
        <input type="text" value="{{ request.get_full_path }}" style="display: none" name="url">
        <button type="submit" class="btn btn-success">Create</button>

    </form>
{% endblock %}

blog/templates/blog/base.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
    <body>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% block blog_container %}

                {% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <a href="{% url 'blog:add' %}">
                            <button type="button" class="btn btn-primary mt-3 mb-2">Create Post</button>
                        </a>
                        <a href="{% url 'users:old_post' %}" style="text-decoration: none">

                            <li class="list-group-item list-group-item-light">Old Posts</li>

                        </a>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">
                            <body onLoad="initClock()">

                            <div id="timedate">
                                <a id="mon">January</a>
                                <a id="d">1</a>,
                                <a id="y">0</a><br />
                                <a id="h">12</a> :
                                <a id="m">00</a>:
                                <a id="s">00</a>:
                                <a id="mi">000</a>
                            </div>

                        </li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    <script>
        // START CLOCK SCRIPT

        Number.prototype.pad = function(n) {
            for (var r = this.toString(); r.length < n; r = 0 + r);
            return r;
        };

        function updateClock() {
            var now = new Date();
            var milli = now.getMilliseconds(),
                sec = now.getSeconds(),
                min = now.getMinutes(),
                hou = now.getHours(),
                mo = now.getMonth(),
                dy = now.getDate(),
                yr = now.getFullYear();
            var months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
            var tags = ["mon", "d", "y", "h", "m", "s", "mi"],
                corr = [months[mo], dy, yr, hou.pad(2), min.pad(2), sec.pad(2), milli];
            for (var i = 0; i < tags.length; i++)
                document.getElementById(tags[i]).firstChild.nodeValue = corr[i];
        }

        function initClock() {
            updateClock();
            window.setInterval("updateClock()", 1);
        }

        // END CLOCK SCRIPT
    </script>
    </body>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block blog_container %}

{#    {% block title__ %}#}
{#        {{ title }}#}
{#    {% endblock %}#}
    {% if message %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endif %}
    {% if error_message %}
        <div class="alert alert-warning" role="alert">
            {{ error_message }}
        </div>
    {% endif %}
    {% for post in posts %}

        <br>
        <div class="card">
            <div class="card-header">
                <a href="#" style="text-decoration: none">{{ post.author }}</a>
                <small class="text-muted ml-2" >{{ post.date_posted }}</small>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content|truncatewords:50 }}</p>
                <a href="{% url 'blog:about' post.id %}" class="btn btn-primary">Read</a>
                {% if post.author == user %}
                    <a href="{% url 'blog:update' post.id %}" class="btn btn-success">Update</a>
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ forloop.counter }}">
                        Delete
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Are you sure you want do delete</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {{ post.title }}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    <a href="{% url 'blog:delete' post.id %}">
                                        <button type="button" class="btn btn-danger">Delete</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>

    {% endfor %}

{% endblock  %}

blog/templates/blog/update.html
{% extends 'blog/base.html' %}

{% block blog_container %}
    <form action="{% url 'blog:update' post.id %}"  method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleFormControlInput1">Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="{{ post.title }}" value="{{ post.title }}" name="title">
        </div>

        <div class="form-group">
            <label for="exampleFormControlTextarea1"> Content</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="20" name="content">
                {{ post.content }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-warning">Update</button>
        <a href="{% url 'users:home' %}">
            <button class="btn btn-secondary">Cancel</button>
        </a>

    </form>
{% endblock %}