bbms_v2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('blog/', include('blog.urls'))
]

blog/urls.py
from django.urls import path, include
from blog import views
app_name = 'blog'

urlpatterns = [
    path('about/post<int:post_id>/', views.about, name='about'),
    path('delete/post=<int:post_id>/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
    path('update/post=<int:post_id>/', views.update_blog, name='update'),
    path('comment/at/post=<int:post_id>/', views.add_comment, name='add_comment'),
    path('reply/at/comment=<int:comment_id>/', views.add_reply, name='add_reply'),
    path('delete/comment=<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('delete/reply=<int:reply_id>/', views.delete_reply, name='delete_reply'),
    path('edit/comment=<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('edit/reply=<int:reply_id>/', views.edit_reply, name='edit_reply'),

]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [

    path('', views.home, name='home'),
    path('old/', views.old_home, name="old_post"),
    path('signup/donor/', views.sig_don, name='sig_don'),
    path('create/donor/', views.crp_don, name='crp_don'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('update/profile/', views.update, name='update'),
    path('signup/hospital/', views.sig_hos, name='sig_hos'),
    path('create/hospital/', views.crp_hos, name='crp_hos'),
    path('hospital/search/donor/', views.search_donor, name='search_donor'),
    path('request/donor<int:donor_user_id>/bg<str:blood_group>/city<str:city>/', views.make_request, name='make_request'),
    # blood_group, city, request_id
    path('undo/req/bg<str:blood_group>/city<str:city>/id=<int:request_id>/', views.undo_request, name='undo_request'),
    path('donor/new/request/view/', views.request_view_donor, name='request_view_donor'),
    path('donor/accept/request/request_id=<int:request_id>/', views.accept_request, name='accept_request'),
    path('donor/reject/request/request_id=<int:request_id>/', views.reject_request, name='reject_request'),
    path('hospital/view/repo/', views.view_repo, name='view_repo'),
    path('hospital/add/blood/repo', views.add_blood, name='add_blood'),
    path('hospital/remove/blood/repo', views.remove_blood, name='remove_blood'),
    path('hospital/active/request/', views.active_reqs, name='active_reqs'),
    path('hospital/approve/req=<int:request_id>/', views.approve, name='approve'),
    path('hospital/history/', views.view_history, name='view_history'),
    path('tongle', views.change, name='tongle'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
# Create your models here.


class CustomUser(AbstractUser):
    is_donor = models.BooleanField(default=False)
    is_hospital = models.BooleanField(default=False)


class Donor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    contact = models.IntegerField(default=0000000000)
    age = models.IntegerField(default=0)
    blood_group = models.CharField(max_length=4)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=22)
    pin_code = models.IntegerField(default=000000)
    available = models.BooleanField(default=True)
    # no_accepted = models.IntegerField(default=0)
    # no_rejected = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user.username} Profile'


class Hospital(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    contact = models.IntegerField(default=0000000000)
    registration_id = models.CharField(max_length=10)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=22)
    pin_code = models.IntegerField(default=000000)

    def __str__(self):
        return f'{self.user.username} Hospital'


class Request(models.Model):
    donor_id = models.IntegerField(default=-1)
    hospital_id = models.IntegerField(default=-1)
    blood_group = models.TextField(max_length=4)
    status = models.IntegerField(default=0)
    date_requested = models.DateField(null=True, blank=True)
    date_rejected = models.DateField(null=True, blank=True)
    date_approved = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.hospital_id} to {self.donor_id}'

    # pending = 1
    # accepted = 2
    # rejected = 3
    # approved = 4
    # rejection_viewed = 5


class Reward(models.Model):
    req = models.OneToOneField(Request, on_delete=models.CASCADE)
    amount = models.DecimalField(default=0.0, decimal_places=2, max_digits=5)
    date_rewarded = models.DateField(null=True, blank=True)


class HospitalRepository(models.Model):
    hospital_user_id = models.IntegerField(default=-1)
    blood_group = models.TextField(max_length=4)
    quantity = models.IntegerField(default=0)
    plasma_count = models.IntegerField(default=10)


class Reason(models.Model):
    request = models.OneToOneField(Request, on_delete=models.CASCADE)
    decline_reason = models.TextField(max_length=300)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=30, required=True)

    class Meta:
        User = get_user_model()
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class HospitalSignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=40, required=True)

    class Meta:
        User = get_user_model()
        model = User
        fields = ('username', 'first_name', 'email', 'password1', 'password2')

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from . forms import SignUpForm, HospitalSignUpForm
from . models import *
from blog.models import Post
# Create your views here.


def sig_don(request):

    context = {
        'form_user': SignUpForm,
        'title': "VowForRed -Signup",
    }
    if request.user.is_authenticated:
        return redirect('users:home')
    if request.method == 'POST':
        form_user = SignUpForm(request.POST)
        if form_user.is_valid():
            form_user.save()
            username = form_user.cleaned_data.get('username')
            raw_pass = form_user.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_pass)
            user.is_donor = True
            user.save()
            login(request, user)
            # print(user)
            return redirect('users:crp_don')
        else:
            return render(request, 'users/signup.html', context)
    else:
        return render(request, 'users/signup.html', context)


def crp_don(request):

    if not request.user.is_authenticated:
        return redirect('users:home')
        # return render(request, 'users/crp_don.html')
    if request.method == "POST":
        user = request.user
        new_donor = Donor()
        if int(request.POST["age"]) > 21:
            print(user)
            new_donor.user = user
            new_donor.contact = int(request.POST["contact"])
            new_donor.blood_group = request.POST["blood_group"]
            new_donor.age = int(request.POST["age"])
            new_donor.city = request.POST["city"]
            new_donor.state = request.POST["state"]
            new_donor.pin_code = int(request.POST["pin_code"])
            new_donor.save()
            return redirect('users:home')
        else:
            context = {
                'error_message': "We Respect Your Heroic Attitude , Once You Come Become 22 come Back Again",
                'title': "VowForRed -Create Profile",

            }
            return render(request, 'users/crp_don.html', context)
    else:
        return render(request, 'users/crp_don.html')


def home(request):

    if request.user.is_authenticated and request.user.is_hospital:
        blood_groups = ["O+", "O-", "A-", "A+", "B-", "B+", "AB-", "AB+", ]
        repos = HospitalRepository.objects.filter(hospital_user_id=request.user.id)
        flag = True
        for blood in blood_groups:
            quantity = 0
            for repo in repos:
                if repo.blood_group == blood:
                    quantity = quantity + repo.quantity
            if quantity < 10:
                flag = False
                break

        if not flag:
            context = {
                'posts': Post.objects.order_by('-date_posted'),
                'error_message': "Some of Repository is seems to be Empty !!! Please Check Out Now",
                'title': "VowForRed -Home",

            }
            return render(request, 'blog/home.html', context)

        context = {
            'posts': Post.objects.order_by('-date_posted'),
            'title': "VowForRed -Home",

        }
        return render(request, 'blog/home.html', context)

    if request.user.is_authenticated and request.user.is_donor:
        req = Request.objects.filter(donor_id=request.user.id, status=1)
        if req:
            context = {
                'error_message': "You Have some emergency requests !!! Please check in Requests ",
                'title': "VowForRed -Home",

            }
            return render(request, 'blog/home.html', context)
        else:
            context = {
                'posts': Post.objects.order_by('-date_posted'),
                'title': "VowForRed -Home",

            }
            return render(request, 'blog/home.html', context)
    context = {
        'posts': Post.objects.order_by('-date_posted'),
        'title': 'VowForRed -Home',
    }
    return render(request, 'blog/home.html', context)


def old_home(request):

    if request.user.is_authenticated and request.user.is_hospital:
        blood_groups = ["O+", "O-", "A-", "A+", "B-", "B+", "AB-", "AB+", ]
        repos = HospitalRepository.objects.filter(hospital_user_id=request.user.id)
        flag = True
        for blood in blood_groups:
            quantity = 0
            for repo in repos:
                if repo.blood_group == blood:
                    quantity = quantity + repo.quantity
            if quantity < 10:
                flag = False
                break

        if not flag:
            context = {
                'posts': Post.objects.order_by('date_posted'),
                'error_message': "Some of Repository is seems to be Empty !!! Please Check Out Now",
                'title': "VowForRed -Home",

            }
            return render(request, 'blog/home.html', context)

        context = {
            'posts': Post.objects.order_by('date_posted'),
            'title': "VowForRed -Home",

        }
        return render(request, 'blog/home.html', context)

    if request.user.is_authenticated and request.user.is_donor:
        req = Request.objects.filter(donor_id=request.user.id, status=1)
        if req:
            context = {
                'error_message': "You Have some emergency requests !!! Please check in Requests ",
                'title': "VowForRed -Home",

            }
            return render(request, 'blog/home.html', context)
        else:
            context = {
                'posts': Post.objects.order_by('date_posted'),
                'title': "VowForRed -Home",

            }
            return render(request, 'blog/home.html', context)
    context = {
        'posts': Post.objects.order_by('date_posted'),
        'title': "VowForRed -Home",

    }
    return render(request, 'blog/home.html', context)


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('users:home')
    else:
        return redirect('users:home')


def login_user(request):
    if request.user.is_authenticated:
        return redirect('users:home')
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            try:

                if request.user.is_hospital:
                    x = request.user.hospital
                else:
                    x = request.user.donor

                return redirect('users:home')

            except:

                if request.user.is_donor:
                    context = {
                        'error_message': "Please Complete Your Profile for Others Benefit :)",
                        'title': "VowForRed -Create",

                    }
                    return render(request, 'users/crp_don.html', context)
                else:
                    context = {
                        'error_message': "Please Complete Your Profile for Others Benefit :)",
                        'title': "VowForRed -Create",

                    }
                    return render(request, 'users/crp_hos.html', context)
        else:
            context = {
                'error_message': "Username or Password is incorrect",
                'title': "VowForRed -Login",

            }
            return render(request, 'users/login.html', context)
    else:
        return render(request, 'users/login.html', {'title': "VowForRed -Login"})


def update(request):
    if not request.user.is_authenticated:
        return redirect('users:home')
    if request.method == "POST":
        try:
            if request.user.is_donor:
                donor = request.user.donor
                donor.contact = int(request.POST["contact"])
                donor.blood_group = request.POST["blood_group"]
                donor.age = int(request.POST["age"])
                donor.city = request.POST["city"]
                donor.state = request.POST["state"]
                donor.pin_code = int(request.POST["pin_code"])
                donor.save()
                return redirect('users:home')
            else:
                hospital = request.user.hospital
                hospital.contact = request.POST["contact"]
                hospital.registration_id = request.POST["registration_id"]
                hospital.city = request.POST["city"]
                hospital.state = request.POST["state"]
                hospital.pin_code = request.POST["pin_code"]
                hospital.save()
                return redirect('users:home')
        except:
            return redirect('users:home')
    else:
        return render(request, 'users/update.html', {'title': "VowForRed -Update Profile"})


def sig_hos(request):

    context = {
        'form_user': HospitalSignUpForm,
        'title': "VowForRed -SignUp",
    }
    if request.user.is_authenticated:
        return redirect('users:home')
    if request.method == 'POST':
        form_user = HospitalSignUpForm(request.POST)
        if form_user.is_valid():
            form_user.save()
            username = form_user.cleaned_data.get('username')
            raw_pass = form_user.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_pass)
            user.is_hospital = True
            blood_types = ["O+", "O-", "A-", "A+", "B-", "B+", "AB-", "AB+", ]
            user.save()
            login(request, user)
            for blood in blood_types:
                new_repo = HospitalRepository()
                new_repo.blood_group = blood
                new_repo.hospital_user_id = request.user.id
                new_repo.save()
            return redirect('users:crp_hos')
        else:
            return render(request, 'users/signup.html', context)
    else:

users/templates/users/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>
        {% if title %}
            {{ title }}
        {% endif %}
    </title>
</head>
<body style="background:white;">
<nav class="navbar navbar-expand-lg navbar-light bg-light container">
    <a class="navbar-brand" href="#">BloodBank</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:update' %}">Update</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    {% if user.is_donor %}
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'users:request_view_donor' %}">Requests</a>
                            <a class="dropdown-item" href="{% url 'users:view_history' %}">History</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">

                            </a>
                        </div>
                    {% else %}
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'users:search_donor' %}">Make Request</a>
                            <a class="dropdown-item" href="{% url 'users:view_history' %}">History</a>
                            <a class="dropdown-item" href="{% url 'users:active_reqs' %}">Active Requests</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'users:view_repo' %}">Repository</a>
                        </div>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            {% endif %}
        </ul>
        <div class="form-inline my-2 my-lg-0">

            {% if not user.is_authenticated %}
            <a href="{% url 'users:login_user' %}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="">Log In</button>
            </a>
            <a href="#">
                <button class="btn btn-outline-success my-2 my-sm-0 ml-2" type="button" data-toggle="modal" data-target="#exampleModal">
                    Sign Up
                </button>
            </a>
            {% else %}
            {% if user.is_donor %}

                    <form action="{% url 'users:tongle' %}" method="POST" id="av">
                        {% csrf_token %}
                        <div class="custom-control custom-switch">
                            {% if user.donor.available %}
                            <input type="checkbox" class="custom-control-input" id="available" name="available" checked>
                                <label class="custom-control-label mr-3 " for="available">Available</label>
                                {% else %}
                                <input type="checkbox" class="custom-control-input" id="available" name="available">
                                <label class="custom-control-label mr-3" for="available">Unavailable</label>
                                {% endif %}


                            <input type="text" value="{{ request.get_full_path }}" style="display: none" name="url">
                            <input type="submit" style="display: none">


                        </div>
                    </form>


                {% endif %}
                <span class="mr-2"><span class="text-muted">Welcome </span><strong style="color:black">{{ user.username }}</strong></span>
                <a href="{% url 'users:logout_user' %}">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="">Logout</button>
                </a>
            {% endif %}

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Please Select Your Type</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div style="text-align: center">
                                I would like to Signing Up as
                            </div>
                        </div>
                        <div class="container mb-1" style="text-align: center;padding-left: 33%;padding-right: 35%;"">
                            <a href="{% url 'users:sig_hos' %}"><button type="button" class="btn btn-primary "  >Hospital</button></a>
                            <a href="{% url 'users:sig_don' %}"><button type="button" class="btn btn-primary ">Donor</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}

    {% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script>

    $("#available").on('click',function () {
        $('#av').submit();

    })

</script>
</body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}

{% block content %}
    <p><strong>Hare Krishna!!!</strong></p>
    {% if error_message %}
        <div class="p-2 mb-1 mt-2 bg-warning text-dark" style="text-align: center"><strong>{{ error_message }}</strong></div>
    {% endif %}
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="" style="width: 100% ; text-align: center">
        <h2><div class="p-3 mb-2 bg-info text-white"><strong>Login</strong></div></h2>
    </div>
   {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
    {% endif %}
    <div style="margin-right: 25%; margin-left: 25%; width: 50%; margin-top: 5%;">
        <form action="{% url 'users:login_user' %}" method="POST">
            {% csrf_token %}
          <div class="form-group">
            <label >Username</label>
            <input type="text" class="form-control"  placeholder="Enter Username" name="username" required >
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

users/templates/users/requests_view_donor.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="" style="width: 100% ; text-align: center">
        <h2><div class="p-3 mb-2 bg-info text-white"><strong>Blood Request</strong></div></h2>
    </div>

   {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
    {% endif %}

    {% if blood_request %}
        <table class="table table-hover mt-2" >
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Hospital Name</th>
                <th scope="col">City</th>
                <th scope="col">Contact</th>
                <th scope="col">Date</th>
                <th scope="col">Action</th>
                <th scope="col"></th>

            </tr>
            </thead>
            <tbody>

            {% for req in blood_request %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ req.1 }}</td>
                    <td>{{ req.3 }}</td>
                    <td>{{ req.2 }}</td>
                    <td>{{ req.0.date_requested }}</td>
                    <td>
                        <a href="{% url 'users:accept_request' req.0.id%}">
                            <button class="btn btn-success">Accept</button>
                        </a>
                        <a href="#">
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal2">
                                Reject
                            </button>
                            <form action="{% url 'users:reject_request' req.0.id %}" method="post">
                                {% csrf_token %}
                                <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Enter a Valid Reason</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name = "reasons"></textarea>

{#                                                <textarea name = "reasons" rows="8" cols="50" style="font: -apple-system-short-headline">#}
{##}
{#                                                </textarea>#}
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Submit</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </a>
                    </td>
                </tr>
            {% endfor%}

            </tbody>
        </table>

    {% endif %}
    <!-- Modal -->


{% endblock %}

users/templates/users/search_donor.html
{% extends 'users/base.html' %}

{% block content %}

    <div class="" style="width: 100% ; text-align: center">
        <h2><div class="p-3 mb-2 bg-info text-white"><strong>Search Donors</strong></div></h2>
    </div>

   {% if error_message %}
        <div class="alert alert-danger mt-2" role="alert">
            {{ error_message }}
        </div>
    {% endif %}

    <form class="form-inline mt-2" method="POST" action="{% url 'users:search_donor' %}" >
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Blood Group" aria-label="Search" name="blood_group" pattern="(A|B|AB|O)[+|-]" required>
        <input class="form-control mr-sm-2" type="search" placeholder="Enter City" aria-label="Search" name="city" required>
        <button class="btn btn-outline-success my-3 my-sm-0" type="submit">Search</button>
    </form>

    {% if donors %}
        <table class="table table-hover mt-2" >
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">City</th>
                <th scope="col">State</th>
                <th scope="col">Contact</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>

            {% for donor in donors %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ donor.0.user.first_name }} {{ donor.0.user.last_name }}</td>
                    <td>{{ donor.0.city }}</td>
                    <td>{{ donor.0.state }}</td>
                    <td>{{ donor.0.contact }}</td>
                    <td>
                        <a href="#">
                            {% if donor.1 == 1 %}
                                <button class="btn btn-info">Pending</button>
                                <a href="{% url 'users:undo_request' blood_group city donor.2 %}">
                                    <button class="btn btn-danger">Cancel</button>
                                </a>
                            {% elif donor.1 == 2 %}
                                <button class="btn btn-success">Accepted</button>
                            {% elif donor.1 == 3 %}
                                <button class="btn btn-danger">Rejected</button>
                            {% elif donor.1 == 0 %}
                                <a href="{% url 'users:make_request' donor.0.user.id blood_group city%}">
                                    <button class="btn btn-primary">Request</button>
                                </a>
                            {% endif %}
                        </a>
                    </td>
                </tr>
            {% endfor%}

            </tbody>
        </table>

    {% endif %}
{% endblock %}